%.min.js : %.js
	echo "Arena/$@: JS compression"
	yui-compressor --verbose --line-break 70 --charset UTF-8 -o $@ $<

all: \
	radiaki.min.js \
	anazitisi.min.js \
	arena.min.js \
	cpanel.min.js \
	efoplismos.min.js \
	enimerosi.min.js \
	epanel.min.js \
	kinisi.min.js \
	kitapi.min.js \
	online.min.js \
	partida.min.js \
	peximo.min.js \
	profinfo.min.js \
	prosklisi.min.js \
	sizitisi.min.js \
	skiniko.min.js
